"use client";

// import type { Metadata } from "next";
import "./globals.scss";
import React from "react";
import ClientProviders from "@/components/clientProviders";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import "../../nprogress.css";
import nProgress from "nprogress";
import { usePathname } from "next/navigation";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
nProgress.configure({ showSpinner: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  React.useEffect(() => {
    nProgress.start();
    if (typeof window !== "undefined") {
      nProgress.done();
    }
  }, [pathname]);

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
        <link rel="stylesheet" href="nprogress.css" />
      </head>
      <body>
        <Provider store={store}>
          <ClientProviders>{children}</ClientProviders>
        </Provider>
      </body>
    </html>
  );
}
